# Generated by Django 4.1.6 on 2023-02-15 14:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], max_length=60)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('CANCELED', 'Canceled'), ('RESELL', 'Resell'), ('SUCCESS', 'Success')], max_length=20)),
                ('cancel_request_time', models.DateTimeField(blank=True, null=True)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('reserver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.PositiveIntegerField()),
                ('count_of_seat', models.PositiveIntegerField()),
                ('count_of_rows', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('CINEMA', 'Cinema'), ('RESTAURANT', 'Restaurant'), ('THEATER', 'Theater')], max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('business_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FAILED', 'Failed'), ('PENDING', 'Pending'), ('SUCCESS', 'Success')], max_length=20)),
                ('amount', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.reservation')),
                ('reserver_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transaction', to='main.account')),
                ('seat_owner_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='transactions', to='main.account')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('position', models.CharField(choices=[('FIRST_ROW', 'First Row'), ('LAST_ROW', 'Last Row'), ('MIDDLE_ROWS', 'Middle Rows')], max_length=12)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('UNRESERVED', 'Unreserved')], max_length=12)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.seat'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='seat_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Resell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_price', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)])),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.reservation')),
                ('reserver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
